<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model
{
    //
    protected $guarded=[];
    public function getRouteKeyName()
    {
        return "name"; // TODO: Change the autogenerated stub
    }

    public function thread(){

        return $this->hasMany(Thread::class);

    }

}
